create SpringBoot Custom Plugin Template
mia-platform-marketplace/SpringBoot-Custom-Plugin-Template pull request #1
Opened 2019-12-09 15:55 UTC by Luca-Ferrera

2019-12-10 10:10 UTC, fredmaggiowski requested changes

2019-12-10 10:10 UTC, fredmaggiowski commented on .gitignore
> +*.iml
Add DS_Store, build and intermediates directories etc.

2019-12-10 10:10 UTC, fredmaggiowski commented on config/Dockerimage
> +%NEXUS_HOSTNAME%/%CUSTOM_PLUGIN_IMAGE_NAME%
This file is not needed anymore, @JGiola am I right?

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/CPController.java
> +
```suggestion
```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/Application.java
> +
```suggestion
```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/SwaggerConfig.java
> +
```suggestion
```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/SwaggerConfig.java
> +
```suggestion
```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/CPDecorator.java
> +
```suggestion
```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/CPRequestWrapper.java
> +
```suggestion
```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/FilterServletInputStream.java
> +public class FilterServletInputStream extends ServletInputStream {
What's the purpose of this class?

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/FilterServletOutputStream.java
> +}
```suggestion
}

```

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/LoggingInterceptor.java
> +        //logger.info("preHandle - request [" + request + "]");
Remove commented code.

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/LoggingInterceptor.java
> +        //logger.info("postHandle - response [" + response + "]");
Remove commented code

2019-12-10 10:10 UTC, fredmaggiowski commented on src/main/java/eu/miaplatform/customplugin/springboot/lib/Options.java
> +    }
```suggestion
    }

```

2019-12-10 10:10 UTC, fredmaggiowski commented on tag.sh
> +# * Copyright 2019 Mia srl
Remove *

2019-12-19 10:02 UTC, Antolas approved these changes

2019-12-19 10:04 UTC, merged